# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Eodms
                                 A QGIS plugin
 A plugin used to access the EODMS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-05-19
        copyright            : (C) 2022 by Kevin Ballantyne/Natural Resources
                                Canada
        email                : eodms-sgdot@nrcan-rncan.gc.ca
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Eodms class from file Eodms.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .eodms import Eodms
    return Eodms(iface)
