# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SettingsDialog
                                 A QGIS plugin
 A plugin used to access the EODMS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-05-19
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Kevin Ballantyne/Natural Resources Canada
        email                : eodms-sgdot@nrcan-rncan.gc.ca
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""



import os
from eodms_rapi import EODMSRAPI

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'settings_dialog_base.ui'))


class SettingsDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None, eodms=None):
        """Constructor."""
        super(SettingsDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        # self.butLogin.clicked.connect(self.login)

        self.eodms = eodms

        self.username = self.eodms.get_setting('username')
        self.password = self.eodms.get_setting('password')
        self.attempts = self.eodms.get_setting('attempts')
        self.log_path = self.eodms.get_setting('log')
        self.query_timeout = self.eodms.get_setting('query_timeout')
        self.order_timeout = self.eodms.get_setting('order_timeout')

        self.txtUser.setText(self.username)
        self.txtPass.setText(self.password)
        self.txtAttempts.setText(self.attempts)
        self.txtLog.setText(self.log_path)
        self.txtQTimeout.setText(self.query_timeout)
        self.txtOTimeout.setText(self.order_timeout)

        # self.buttonBox.accepted.connect(self.save_settings)

    # def save_settings(self):

        # username = self.edtUser.text()
        # password = self.edtPass.text()



        # QgsMessageLog.logMessage(msg_tr, tag, level, notify_user)

        # rapi = EODMSRAPI(username, password)